apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: vonage-gitops-domain
  title: Vonage Domain Deployment Targets
  description: Create one of more release channels for a domain. Each domain release channel can be tied to multiple clusters
  tags:
    - recommended
    - cerebro
spec:
  owner: architecture@vonage.com
  templater: cookiecutter
  type: resource
  path: '.'
  schema:
    required:
      - component_id
      - project_description
    properties:
      component_id:
        title: Project Name
        type: string
        description: Unique name of the project
      project_description:
        title: Description
        type: string
        description: Help others understand what this service does
       