apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vonage-gitops-domain
  title: Deployment GitOps Template 
  description: Create one of more release channels for a domain. Each domain release channel can be tied to multiple clusters
  tags:
    - recommended
    - cerebro
spec:
  owner: architecture@vonage.com
  type: resource
  parameters:
           
    - title: Fill in more steps
      required:
        - cre
      properties:
        name:
          title: cre
          type: string
          description: My custom name for the component
          ui:field: MyCustomExtension
 # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
  steps:
    - id: fetch
      name: Template Docs Skeleton
      action: fetch:template
      input:
        url: ./mainSkeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/Latest/catalog-info.yaml"

 
  output:
    remoteUrl: ${{ steps.publish.output.remoteUrl }}
    entityRef: ${{ steps.register.output.entityRef }}
