apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: channel-{{cookiecutter.component_id | jsonify}}-latest
  description: {{cookiecutter.project_description | jsonify}}
  annotations:
    github.com/project-slug: {{cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}}
    backstage.io/techdocs-ref: url:{{"https://" + cookiecutter.destination.host + "/" + cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}}
spec:
  type: channel
  lifecycle: production
  owner: {{cookiecutter.owner | jsonify}}
