apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: channel-${{values.name}}-latest
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: url:${{"https://" + values.destination.host + "/" + values.destination.owner + "/" + values.destination.repo}}
spec:
  type: channel
  lifecycle: production
  owner: ${{values.owner | dump}}
